Django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls', namespace='events')),
    path('users/', include('users.urls', namespace='users'))
]

events/urls.py
from django.urls import path
from . import views
app_name = 'events'
urlpatterns = [
    # events_story views
    path('', views.home, name='home'),
    path('stories', views.events_story_list, name='story-list'),
    path('stories/<int:story_id>', views.events_story_detail, name='story-detail'),
    path('stories/add', views.create_event, name='create-event'),
    path('stories/new', views.event_added, name='event_added'),
    path('stories/results', views.search_results, name='search-results'),
    path('stories/results/none', views.search_results_none, name='search-results_none'),
    path('stories/edit/<int:story_id>', views.edit_event, name='edit'),
    path('stories/updated/<int:story_id>', views.event_changed, name='event_changed'),
    path('stories/delete/<int:story_id>', views.delete_event, name='delete'),
    path('stories/registered', views.events_story_registered, name='event_registered'),
    path('stories/liked', views.events_story_like, name='event_like'),
    path('stories/disliked', views.events_story_dislike, name='event_dislike'),
    path('stories/description', views.events_story_description, name='event_description'),
    path('stories/comments', views.view_comments, name='view_comments'),
    path('stories/comments/new', views.add_comment, name='add_comment'),
    path('stories/comments/edit/<int:comment_id>', views.edit_comment, name='edit_comment'),
    path('stories/comments/updated/<int:comment_id>', views.comment_changed, name='comment_changed'),
    path('stories/comment/delete/<int:comment_id>', views.delete_comment, name='delete_comment'),
    path('members', views.members, name='members'),
    path('contact', views.contact, name='contact'),
    path('media', views.media, name='media'),
    path('isvt', views.about, name='about'),
    path('directory', views.directory, name='directory'),
    path('join', views.join, name='join'),
    path('performer/facebook/<int:story_id>', views.performer_facebook, name='performer_facebook'),
    path('performer/facebook/added/<int:story_id>', views.performer_facebook_added, name='performer_facebook_added'),
]

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    # events_story views
    path('register', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('logout', views.logout_user, name='logout'),
    path('login', views.login_user, name='login'),
    path('update/<str:username>', views.update_profile, name='update_profile'),
    path('edit/<str:username>', views.edit_profile, name='edit_profile'),
]

events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.

class EventsStory(models.Model):
    title = models.CharField(max_length=200)
    date_month = models.CharField(max_length=50)
    date_day = models.CharField(max_length=20)
    date_weekday = models.CharField(max_length=50)
    time = models.CharField(max_length=50)
    score = models.IntegerField(default=0)
    author = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(auto_now_add=True)
    registered = models.IntegerField(default=0)
    description = models.TextField()
    performers = models.CharField(max_length=100)
    role = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    url = models.CharField(max_length=500)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('events:story-detail', args=[self.id])


class Comment(models.Model):
    title = models.CharField(max_length=200)
    comment = models.TextField()
    author = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('events:view_comments')


# hard-coded user accounts
regular_user = {"username": "rana", "password": "regular"}
admin_user = {"username": "admin", "password": "admin"}

events/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import regular_user, admin_user, EventsStory, User, Comment
from actions.models import Action
from django.http import JsonResponse
import requests
import boto3
from django.template.loader import render_to_string
from django.contrib.auth import authenticate


# Create your views here.
def events_story_list(request):
    events_stories = EventsStory.objects.all()
    sort = request.POST.get('sort-by-register')
    if sort == 'Registered':
        events_stories = EventsStory.objects.order_by('-registered')
    sort1 = request.POST.get('sort-by-date')
    if sort1 == 'Recently updated':
        events_stories = EventsStory.objects.order_by('-date_posted')
    return render(request,
                  "events/events_story/list.html",
                  {"stories": events_stories}
                  )


def events_story_detail(request, story_id):
    story = EventsStory.objects.get(pk=story_id)

    endpoint = "https://en.wikipedia.org/w/api.php"
    parameters = {
        "action": "query",
        "list": "search",
        "srsearch": story.title,
        "format": "json",
    }

    try:
        response = requests.get(endpoint, params=parameters)
        wikidata = response.json()
        top_wiki_title = wikidata["query"]["search"][0]["title"]
    except IndexError:
        top_wiki_title = None

    return render(request,
                  "events/events_story/detail.html",
                  {"story": story,
                   "top_wiki_title": top_wiki_title}
                  )


def home(request):
    if request.session.get("username", False):
        actions = Action.objects.all().order_by('-created')

        return render(request,
                      "events/events_story/dashboard.html",
                      {"actions": actions}
                      )

    else:
        return render(request,
                      "events/home.html",
                      )


def create_event(request):
    return render(request,
                  "events/events_story/add.html",
                  )


def event_added(request):
    if request.method == 'POST':
        # process the form
        title = request.POST.get('add-title')
        description = request.POST.get('add-description')
        startdate = request.POST.get('add-start date')
        starttime = request.POST.get('add-start time')
        location = request.POST.get('add-location')
        guests = request.POST.get('add-guests')
        role = request.POST.get('add-role')

        # content moderation
        endpoint = "https://isvttextmod.cognitiveservices.azure.com/contentmoderator/moderate/v1.0/ProcessText/Screen"
        parameters = {
            'classify': True,
        }
        headers = {
            'Content-Type': 'text/plain',
            'Ocp-Apim-Subscription-Key': '5d85180a097b4949ba5bc2b583c6569f',
        }
        data = description
        response = requests.post(endpoint, params=parameters, headers=headers, data=data)
        response_json = response.json()
        review_recommended = response_json["Classification"]["ReviewRecommended"]
        if review_recommended:
            messages.add_message(request, messages.ERROR,
                                 "Your description contains inappropriate contents. Please change it.")
            return redirect('events:create-event')

        user = User.objects.get(username=request.session.get("username"))

        es = EventsStory(
            title=title,
            description=description,
            date_weekday=startdate,
            date_month=startdate,
            # date_day=startdate,
            time=starttime,
            location=location,
            performers=guests,
            author=request.session.get('username'),
            user=user,
            role=role,
        )
        es.save()

        # log the action
        action = Action(
            user=user,
            verb="created the new story",
            target=es
        )
        action.save()
        messages.add_message(request, messages.SUCCESS, "You successfully submitted a new event story: %s" % es.title)
        element = es
        return redirect('events:story-detail', element.id)
    else:
        # show the template
        return render(request,
                      "events/events_story/add.html",
                      )


def edit_event(request, story_id):
    story = EventsStory.objects.get(pk=story_id)
    return render(request,
                  "events/events_story/edit.html",
                  {"story": story}
                  )


def event_changed(request, story_id):

    es = EventsStory.objects.get(pk=story_id)

    mturk = request.GET.get('mturk', False)
    if mturk == 'yes':
        user = authenticate(username='mturk', password='mturk')
        request.session['username'] = user.username
        request.session['role'] = user.details.role
    else:
        user = User.objects.get(username=request.session.get("username"))

    if user.id == es.user.id or request.session['role'] == 'admin' or user.username == 'mturk':
        if request.method == 'POST':
            # process the form
            title = request.POST.get('edit-title')
            description = request.POST.get('edit-description')
            print(description)
            startdate = request.POST.get('edit-date')
            starttime = request.POST.get('edit-time')
            location = request.POST.get('edit-location')
            guests = request.POST.get('edit-guests')
            print(guests)
            role = request.POST.get('edit-role')
            print(role)

            if title:
                es.title = title
            if description:
                es.description = description
            if startdate:
                es.startdate = startdate
            if starttime:
                es.starttime = starttime
            if location:
                es.location = location
            if guests:
                es.guests = guests
            if role:
                es.role = role
            es.save()

            # log the action
            action = Action(
                user=user,
                verb="edited a story",
                target=es
            )
            action.save()

            messages.add_message(request, messages.SUCCESS, "You successfully edited an event story: %s" % es.title)
            element = es
            return redirect('events:story-detail', story_id=story_id)
        else:
            # show the template
            return render(request,
                          "events/events_story/edit.html",
                          )


def delete_event(request, story_id):
    instance = EventsStory.objects.get(id=story_id)
    instance.delete()

    messages.add_message(request, messages.WARNING, "The following event story was deleted: %s" % instance.title)

    return redirect('events:story-list')


def events_story_registered(request):
    # redirect if not logged in
    if not request.session.get("username", False):
        return redirect('events:story-list')

    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        story_id = request.POST.get('story_id')
        try:
            story = EventsStory.objects.get(pk=story_id)
            story.registered = story.registered + 1
            story.save()
            return JsonResponse({'success': 'success', 'registered': story.registered}, status=200)

        except EventsStory.DoesNotExist:
            return JsonResponse({'error': 'No story found with that ID.'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax request.'}, status=400)


def events_story_like(request):
    # redirect if not logged in
    if not request.session.get("username", False):
        return redirect('events:story-list')

    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        story_id = request.POST.get('story_id')
        try:
            story = EventsStory.objects.get(pk=story_id)
            story.score = story.score + 1
            story.save()
            return JsonResponse({'success': 'success', 'score': story.score}, status=200)

        except EventsStory.DoesNotExist:
            return JsonResponse({'error': 'No story found with that ID.'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax request.'}, status=400)


def events_story_dislike(request):
    # redirect if not logged in
    if not request.session.get("username", False):
        return redirect('events:story-list')

    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        story_id = request.POST.get('story_id')
        try:
            story = EventsStory.objects.get(pk=story_id)
            story.score = story.score - 1
            story.save()
            return JsonResponse({'success': 'success', 'score': story.score}, status=200)

        except EventsStory.DoesNotExist:
            return JsonResponse({'error': 'No story found with that ID.'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax request.'}, status=400)


def events_story_description(request):
    # redirect if not logged in
    if not request.session.get("username", False):
        return redirect('events:home')

    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "GET":
        # story_id = request.POST.get('story_id')
        try:
            story = EventsStory.objects.all()
            story.info = story.info
            story.save()
            return JsonResponse({'success': 'success', 'info': story.info}, status=200)

        except EventsStory.DoesNotExist:
            return JsonResponse({'error': 'No data found with that ID.'}, status=200)

templates/events/events_story/comments.html
{% extends "events/base.html" %}
{% load static %}
{% load humanize %}
{% block page-title %}Comments{% endblock %}
{% block title %}
    <div id="title">
        <h2>Comments for Event Story</h2>
    </div><!-- #title -->
{% endblock %}
{% block content %}
    <div class="event-story">
        {% for comment in comments %}
        <h4>{{ comment.title }}</h4>
        <h5>{{ comment.comment }}</h5>
        <h6>Posted by <a href="{% url 'users:profile' comment.user.username %}">{{ comment.user.username }}</a> {{ comment.date_posted }}</h6>

            <form class="edit" action="{% url 'events:edit_comment' comment.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" name="edit" value="Edit Comment">
            </form><!-- #edit -->
            <form class="delete" action="{% url 'events:delete_comment' comment.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" name="delete" value="Delete Comment">
            </form><!-- #delete -->


        {% empty %}
            <li>No comment yet.</li>
        {% endfor %}

        <form id="event-box" action="{% url 'events:add_comment'%}" method="POST">
            <input id="add-title" type="text" name="add-title" placeholder="Title">
            <input id="add-comment" type="text" name="add-comment" placeholder="Add a comment...">

            <input type="submit" name="edit" value="Post">
            {% csrf_token %}
       </form><!-- #event-box -->

    </div><!-- #event-story -->

{% endblock %}

{% block ad %}
    <div id="side-bar">

    </div><!-- #side-bar -->
{% endblock %}

templates/events/events_story/detail.html
{% extends "events/base.html" %}
{% load static %}
{% load humanize %}
{% block page-title %}{{ story.title }}{% endblock %}
{% block title %}
    <div id="title">
        <h2>{{ story.title }}</h2>
        <h6>Calendar</h6>
        <h5>{{ story.date_weekday }}, {{ story.date_month }} {{ story.date_day }} {{ story.time }}</h5>
        <h6>Location</h6>
        <h5>{{ story.location }}</h5>
        <form class="register1">
            <input type="submit" name="register" value="Register">
        </form><!-- #register -->

    </div><!-- #title -->
{% endblock %}
{% block content %}
    <div class="event-story">
        <h2>Overview</h2>
        <h4>ISVT</h4>
        <h5>Created by <a href="{% url 'users:profile' story.user.username %}">{{ story.user.username }}</a> {{ story.date_posted }}</h5>
        <h3>{{ story.title }}</h3>
        <p class="event-description">{{ story.description }}</p>
        {% if request.session.username %}
            <h6><a href="{% url 'events:view_comments'%}">View comments</a></h6>
        {% endif %}
        <h6>Learn more form Wikipedia</h6>
        <p><a href="http://en.wikipedia.org/wiki/{{ top_wiki_title|urlencode }}">{{ top_wiki_title }}</a></p>
    </div><!-- #detail-story -->
    <div class="event-story">
        <div id="performers"><h2>Performers</h2>
            <p class="performers"><a href="{{ story.url }}"> {{ story.performers }}</a> {{ story.role }}</p>
{#            <p class="performers"> {{ story.role }}</p>#}
            {% if request.session.role == "admin" or request.session.username == "admin" %}
                <h6 class="performers"><a href="{% url 'events:performer_facebook' story.id %}"> Facebook</a></h6>
            {% endif %}
        </div><!-- #performers -->
    </div><!-- #event-story -->
{% endblock %}

{% block ad %}
    <div id="side-bar">
        <h2>Attendees</h2>
        <div id="attendees">
            <div class="registered">
                <div class="registered">Registered</div>
                <div class="numR">{{ story.registered }}</div>
            </div><!-- #registered -->
            <div class="interested">
                <div class="interested">Interested</div>
                <div class="numI">{{ story.score }}</div>
            </div><!-- #interested -->
        </div><!-- #attendees -->
        {% if request.session.role == "admin" or request.session.username == story.user.username %}
            <form class="edit" action="{% url 'events:edit' story.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" name="edit" value="Edit Event">
            </form><!-- #edit -->
            <form class="delete" action="{% url 'events:delete' story.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" name="delete" value="Delete Event">
            </form><!-- #delete -->
        {% endif %}
    </div><!-- #side-bar -->
{% endblock %}

templates/events/events_story/edit-comment.html
{% extends "events/base.html" %}
{% load static %}
{#{% load humanize %}#}
{% block scripts %}
    <script src="{% static "JS/jquery-3.6.0.min.js" %}"></script>
    <script src="{% static "JS/scripts.js" %}"></script>
{% endblock %}
{% block page-title %}Edit Events Story{% endblock %}
{% block content %}

    <div id="title-event">
            <h2>Edit Comment</h2>
    </div><!-- #title-event -->
    <div class="event-story">
        <form id="event-box" action="{% url 'events:comment_changed' comment.id %}" method="POST">

            <input id="edit-title" type="text" name="edit-title" value="{{ comment.title }}" placeholder="Title">
            <input id="edit-comment" type="text" name="edit-comment" value="{{ comment.comment }}" placeholder="Add a comment...">

            <input id="save" class="button" type="submit" value="Save">
            {% csrf_token %}
        </form><!-- #event-box -->
            <form id="discard-box" action="{% url 'events:story-list' %}" method="POST">
                <input id="delete" class="button" type="submit" value="Discard">
                {% csrf_token %}
            </form>
    </div><!-- #event-story -->

{% endblock %}

{% block ad %}
    <div id="side-bar">
        <a href="#" class="ad"><img src="{% static "img/ad.jpg" %}" alt="Ad"></a>
        <a href="#" class="ad"><img src="{% static "img/ad.jpg" %}" alt="Ad"></a>
{#        <form class= "newEvent" action="{% url 'events:story-list' %}" method="POST">#}
{##}
{##}
{#        </form>#}
    </div><!-- #side-bar -->
{% endblock %}

templates/events/events_story/edit.html
{% extends "events/base.html" %}
{% load static %}
{#{% load humanize %}#}
{% block scripts %}
    <script src="{% static "JS/jquery-3.6.0.min.js" %}"></script>
    <script src="{% static "JS/scripts.js" %}"></script>
{% endblock %}
{% block page-title %}Edit Event: {{ story.title }}{% endblock %}
{% block content %}

    <div class="event-story">
        <h2>Edit Event: {{ story.title }}</h2>
        <h4><a href="#">{{ story.user.username }}</a> - Host</h4>
        <form id="event-box" action="{% url 'events:event_changed' story.id %}" method="POST">

            <input id="edit-title" type="text" name="edit-title" value="{{ story.title }}" placeholder="Title">
            <input id="edit-description" type="text" name="edit-description" value="{{ story.description }}" placeholder="Description">
            <input id="edit-date" type="text" name="edit-date" value="{{ story.date_weekday }} {{ story.date_month }} {{ story.date_day }}" placeholder="Start Date">
            <input id="edit-time" type="text" name="edit-time" value="{{ story.date_month }}" placeholder="Start Time">
            <h5><a href="#">+ End Date and Time</a></h5>
            <input id="edit-location" type="text" name="edit-location" value="{{ story.location }}" placeholder="Location">
            <input id="edit-guests" type="text" name="edit-guests" value="{{ story.performers }}" placeholder="Guests">
            <input id="edit-role" type="text" name="edit-role" value="{{ story.role }}" placeholder="Role" >

            <input id="save" class="button" type="submit" value="Save">
            {% csrf_token %}
        </form><!-- #event-box -->
        <form id="discard-box" action="{% url 'events:story-list' %}" method="POST">
            <input id="delete" class="button" type="submit" value="Discard">
            {% csrf_token %}
        </form>
    </div><!-- #event-story -->

{% endblock %}

{% block ad %}
    <div id="side-bar">
        <a href="#" class="ad"><img src="{% static "img/ad.jpg" %}" alt="Ad"></a>
        <a href="#" class="ad"><img src="{% static "img/ad.jpg" %}" alt="Ad"></a>
{#        <form class= "newEvent" action="{% url 'events:story-list' %}" method="POST">#}
{##}
{##}
{#        </form>#}
    </div><!-- #side-bar -->
{% endblock %}

templates/events/events_story/isvt-about.html
{% extends "events/base.html" %}
{% load static %}
{% block page-title %}About{% endblock %}
{% block title %}
    <div id="title">
        <h2>About ISVT</h2>
    </div><!-- #title -->
{% endblock %}
{% block content %}
    <div id="about">
        <h4>A collective of Iranian students at Virginia Tech.</h4>
        <p>The Iranian Society at Virginia Tech is a non-religious, non-political student organization aiming to promote Persian culture among Virginia Tech Community and support the Iranian community in Blacksburg and National Capital Region.</p>
    <p>The purpose of this webpage is to serve Iranian students and anyone who is interested in Iranian society at Virginia Tech. You're more than welcome to <a href="{% url 'events:join' %}">become a member</a> and post any personal ads and discussion here.</p>

     </div><!-- #about -->

{% endblock %}

{% block ad %}

{% endblock %}

templates/events/events_story/isvt-executive.html
{% extends "events/base.html" %}
{% load static %}
{% block page-title %}Members Directory{% endblock %}
{% block title %}
    <div id="title">
        <h2>The ISVT Executive Board</h2>
    </div><!-- #title -->
{% endblock %}
{% block content %}
{#    {% for user in users %}#}
        <div id="executive">
            <a href="{% url "users:profile" 'Alex' %}"><h4>Alex Habibi</h4></a>
            <p>Admin</p>
            <a href="{% url "users:profile" 'Fariddedin' %}"><h4>Fariddedin Bazzel</h4></a>
            <p>Admin</p>
            <a href="{% url "users:profile" 'Saeed' %}"><h4>Saeed Behzadi</h4></a>
            <p>Admin</p>
            <a href="{% url "users:profile" 'Deena' %}"><h4>Deena Daneshvaziri</h4></a>
            <p>Admin</p>
            <a href="{% url "users:profile" 'Ali' %}"><h4>Ali Hassani</h4></a>
        <p>Admin</p>

     </div><!-- #directory -->
{#    {% endfor %}#}

{% endblock %}

{% block ad %}

{% endblock %}

templates/events/events_story/list-search-main.html
{% extends "events/base.html" %}
{% load static %}
{#{% load humanize %}#}
{% block scripts %}
    <script src="{% static "JS/jquery-3.6.0.min.js" %}"></script>
    <script src="{% static "JS/scripts.js" %}"></script>
{% endblock %}
{% block page-title %}Events Story{% endblock %}
{% block content %}

    <div id="title-search">
        <h2>Search results</h2>
    </div><!-- #title -->

    {% for story in stories %}
        <div class="event-story">
            <div class="event-date">
                <div class="event-month">{{ story.date_month }}</div>
                <div class="event-day">{{ story.date_day }}</div>
            </div><!-- #event-date -->
{#            {% if request.session.username %}#}
                <div class="registration">
                    <button class="register" data-story-id="{{ story.id }}" data-ajax-url="{% url 'events:event_registered' %}">Register</button>
                    <div class="registered">{{ story.registered }} Registered</div>
                </div>
{#            {% endif %}#}
            <h3 class="event-title"><a href="{% url "events:story-detail" story.id %}" methods="GET">{{ story.title }}</a></h3>
            <p class="event-writer">Created by <a href="{% url 'users:profile' story.user.username %}">{{ story.user.username }}</a></p>
            {% if request.session.username %}
                <div class="event-like">
                    <button class="like">like</button>
                    <div class="score">{{ story.score }}</div>
                    <button class="dislike">dislike</button>
                </div><!-- #event-like -->
                <p class="event-writer">{{ story.date_posted }}</p>
                <p class="event-byline1">Hosted by ISVT</p>
                <form class="add-to-calendar">
                    <input type="submit" name="add" value="Add to Calendar">
                </form><!-- #add-to-calendar -->


            {% else %}
            <p class="event-byline">Hosted by ISVT</p>
            {% endif %}
        </div><!-- #event-story -->
    {% endfor %}

{% endblock %}

{% block ad %}
    <div id="side-bar">
        <a href="#" class="ad"><img src="{% static "img/ad.jpg" %}" alt="Ad"></a>
        <a href="#" class="ad"><img src="{% static "img/ad.jpg" %}" alt="Ad"></a>
    </div><!-- #side-bar -->
{% endblock %}

templates/events/events_story/list.html
{% extends "events/base.html" %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static "CSS/responsive.css" %}">
{% endblock %}
{#{% load humanize %}#}
{% block scripts %}
    <script src="{% static "JS/jquery-3.6.0.min.js" %}"></script>
    <script src="{% static "JS/scripts.js" %}"></script>
{% endblock %}
{% block title %}
    <div id="title">
        <h2>Events</h2>
        <form action="{% url 'events:search-results' %}" method="GET">
            <input type="search" name="search-event" placeholder="search event">
        </form>
        {% if request.session.username %}
            <form class="create-event" action="{% url 'events:create-event' %}" method="POST">
                {% csrf_token %}
                <input type="submit" name="create event" value="Create Event">
            </form>
        {% endif %}
    </div><!-- #title -->
{% endblock %}
{% block filter %}
    <div id="filter-box">
        <h3>Sort by</h3>
        <form id="Sort by" action="{% url 'events:story-list' %}" method="POST">
            {% csrf_token %}
            <input id="sort-by-like" type="submit" name="sort-by-register" value="Registered">
            <input id="sort-by-like" type="submit" name="sort-by-date" value="Recently updated">
        </form>
    </div><!-- #filter-box -->
{% endblock %}
{% block page-title %}Events Story{% endblock %}
{% block content %}

    {% for story in stories %}
        <div class="event-story">
            <div class="event-date">
                <div class="event-month">{{ story.date_month }}</div>
                <div class="event-day">{{ story.date_day }}</div>
            </div><!-- #event-date -->
{#            {% if request.session.username %}#}
                <div class="registration">
                    <button class="register" data-story-id="{{ story.id }}" data-ajax-url="{% url 'events:event_registered' %}">Register</button>
                    <div class="registered">{{ story.registered }} Registered</div>
                </div>
{#            {% endif %}#}
            <h3 class="event-title"><a href="{% url "events:story-detail" story.id %}" methods="GET">{{ story.title }}</a></h3>
            <p class="event-writer">Created by <a href="{% url 'users:profile' story.user.username %}">{{ story.user.username }}</a></p>
            {% if request.session.username %}
                <div class="event-like">
                    <button class="like" data-story-id="{{ story.id }}" data-ajax-url="{% url 'events:event_like' %}">like</button>
                    <div class="score">{{ story.score }}</div>
                    <button class="dislike" data-story-id="{{ story.id }}" data-ajax-url="{% url 'events:event_dislike' %}">dislike</button>
                </div><!-- #event-like -->
                <p class="event-writer">{{ story.date_posted }}</p>
                <p class="event-byline1">Hosted by ISVT</p>
                <form class="add-to-calendar">
                    <input type="submit" name="add" value="Add to Calendar">
                </form><!-- #add-to-calendar -->


            {% else %}
            <p class="event-byline">Hosted by ISVT</p>
            {% endif %}
        </div><!-- #event-story -->
    {% endfor %}

{% endblock %}

{% block ad %}
    <div id="side-bar">
        <a href="#" class="ad"><img src="{% static "img/ad.jpg" %}" alt="Ad"></a>
        <a href="#" class="ad"><img src="{% static "img/ad.jpg" %}" alt="Ad"></a>
    </div><!-- #side-bar -->
{% endblock %}

templates/events/events_story/members.html
{% extends "events/base.html" %}
{% load static %}
{% block page-title %}Members{% endblock %}
{% block title %}
    <div id="title">
        <h2>User Profiles</h2>
    </div><!-- #title -->
{% endblock %}
{% block content %}
    <div id="about">
        {% for user in users %}
            <p>
            <li><a href="{% url "users:profile" user.username %}">{{ user.username }}</a></li>
            <li>Role: {{ user.details.role }}</li>
            </p>
        {% endfor %}
     </div><!-- #about -->

{% endblock %}

{% block ad %}

{% endblock %}