Django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls', namespace='events')),
    path('users/', include('users.urls', namespace='users'))
]

events/urls.py
from django.urls import path
from . import views
app_name = 'events'
urlpatterns = [
    # events_story views
    path('', views.home, name='home'),
    path('stories', views.events_story_list, name='story-list'),
    path('stories/<int:story_id>', views.events_story_detail, name='story-detail'),
    path('stories/add', views.create_event, name='create-event'),
    path('stories/new', views.event_added, name='event_added'),
    path('stories/results', views.search_results, name='search-results'),
    path('stories/results/none', views.search_results_none, name='search-results_none'),
    path('stories/edit/<int:story_id>', views.edit_event, name='edit'),
    path('stories/updated/<int:story_id>', views.event_changed, name='event_changed'),
    path('stories/delete/<int:story_id>', views.delete_event, name='delete'),
    path('stories/registered', views.events_story_registered, name='event_registered'),
    path('stories/liked', views.events_story_like, name='event_like'),
    path('stories/disliked', views.events_story_dislike, name='event_dislike'),
    path('stories/description', views.events_story_description, name='event_description'),
    path('stories/comments', views.view_comments, name='view_comments'),
    path('stories/comments/new', views.add_comment, name='add_comment'),
    path('stories/comments/edit/<int:comment_id>', views.edit_comment, name='edit_comment'),
    path('stories/comments/updated/<int:comment_id>', views.comment_changed, name='comment_changed'),
    path('stories/comment/delete/<int:comment_id>', views.delete_comment, name='delete_comment'),
    path('members', views.members, name='members'),
    path('contact', views.contact, name='contact'),
    path('media', views.media, name='media'),
    path('isvt', views.about, name='about'),
    path('directory', views.directory, name='directory'),
    path('join', views.join, name='join'),
    path('performer/facebook/<int:story_id>', views.performer_facebook, name='performer_facebook'),
    path('performer/facebook/added/<int:story_id>', views.performer_facebook_added, name='performer_facebook_added'),
]

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    # events_story views
    path('register', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('logout', views.logout_user, name='logout'),
    path('login', views.login_user, name='login'),
    path('update/<str:username>', views.update_profile, name='update_profile'),
    path('edit/<str:username>', views.edit_profile, name='edit_profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.forms import ModelForm
from django.urls import reverse
# Create your models here.


class Details(models.Model):
    ROLES = (
        ('admin', 'admin'),
        ('registered', 'registered'),
        ('unregistered', 'unregistered'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(default="registered", max_length=50, choices=ROLES)


@receiver(post_save, sender=User)
def create_user_details(sender, instance, created, **kwargs):
    if created:
        Details.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_details(sender, instance, **kwargs):
    instance.details.save()

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate
from actions.models import Action
# from users.models import UserEditForm
from django.urls import reverse

# Create your views here.


def profile(request, username):
    user1 = get_object_or_404(User, username=username)
    if request.session.get("username", False):
        usr_obj = User.objects.get(username=request.session.get("username")) #username is unique
        user_id = getattr(usr_obj, "id")
        actions = Action.objects.filter(user_id=user_id).order_by('-created')
        return render(request,
                      "users/user/profile.html",
                      {"actions": actions, "user": user1},
                      )
    else:
        user1 = User.objects.get(username=username)
        return render(request,
                      "users/user/profile.html",
                      {"user": user1}
                      )


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = User.objects.create_user(username, email, password)
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.save()

        user1 = authenticate(username=username, password=password)
        if user is not None:
            request.session['username'] = user.username
            request.session['role'] = user.details.role

        # log the action
        action = Action(
            user=user,
            verb="joined the ISVT",
            target=user
        )
        action.save()

        messages.add_message(request, messages.SUCCESS, "You successfully registered with the username: %s" % user.username)

        return redirect('events:home')

    else:
        return render(request,
                      "users/user/register.html",
                      )


def login_user(request):
    username = request.POST.get("username")
    password = request.POST.get("pw")

    user = authenticate(username=username, password=password)
    if user is not None:
        request.session['username'] = user.username
        request.session['role'] = user.details.role
        messages.add_message(request, messages.SUCCESS,
                             "You successfully logged in.")
    else:
        messages.add_message(request, messages.ERROR,
                             "Invalid username or password.")
    return redirect('events:home')


def logout_user(request):
    del request.session['username']
    del request.session['role']
    return redirect('events:home')


def edit_profile(request, username):
    username = User.objects.get(username=username)  # username is unique
    return render(request,
                  "users/user/useredit_form.html",
                  {"username": username}
                  )


def update_profile(request, username):
    user = User.objects.get(username=username)
    if request.method == 'POST':
        # process the form
        first_name = request.POST.get('edit-first-name')
        last_name = request.POST.get('edit-last-name')
        role = request.POST.get('edit-role')
        password = request.POST.get('edit-password')

        # user = User.objects.get(username=request.session.get("username"))

        ur = User.objects.all()[0]
        if first_name:
            user.first_name = first_name
        if last_name:
            user.last_name = last_name
        if role:
            user.details.role = role
        # if password:
        if len(password) != 0:
            user.set_password(password)
        user.save()

        return redirect('users:profile', username=username)
    else:
        # show the template
        return render(request,
                      "users/user/useredit_form.html",
                      )

templates/users/user/profile.html
{% extends "events/base.html" %}
{% load static %}
{% block page-title %}Profile for {{ user.username }}{% endblock %}
{% block title %}
    <div id="title">
        <h2>Profile for "{{ user.username }}"</h2>
    </div><!-- #title -->
{% endblock %}
{% block content %}
    <div class="event-story">
        <dl>
            <dt>Username</dt>
            <dd>{{ user.username }}</dd>
            <dt>First name</dt>
            <dd>{{ user.first_name }}</dd>
            <dt>Last name</dt>
            <dd>{{ user.last_name }}</dd>
            <dt>Role</dt>
            <dd>{{ user.details.role }}</dd>
            <dt>Password</dt>
            <dd>{{ user.password.decode }}</dd>
            <dt>Email address</dt>
            <dd>{{ user.email }}</dd>
            <dt>Based in:</dt>
            <input type="checkbox" class="blacksburg" name="blacksburg"><p>Blacksburg</p>
            <input type="checkbox" name="national capitol region" value="National Capital Region"><p>National Capital Region</p>
            <form class="calendar-open">
                <a href="https://calendar.google.com/"><input type="submit" name="calendar" value="Configure Calendar and Events"></a>
            </form><!-- #calendar -->
            {% if request.session.role == "admin" or request.session.username == user.username %}
                <form class="edit" action="{% url 'users:edit_profile' user.username %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" name="edit" value="Edit Profile">
                </form><!-- #edit -->
            {% endif %}
        </dl>

        {% include "actions/action/feed.html" %}
    </div>

{% endblock %}

{% block ad %}

{% endblock %}

templates/users/user/register.html
{% extends "events/base.html" %}
{% load static %}
{#{% load humanize %}#}
{% block scripts %}
    <script src="{% static "JS/jquery-3.6.0.min.js" %}"></script>
    <script src="{% static "JS/scripts.js" %}"></script>
{% endblock %}
{% block page-title %}Register User{% endblock %}
{% block content %}

    <div id="title-event">
        <h2>Register User</h2>
    </div><!-- #title -->

        <form id="register-user" action="{% url 'users:register' %}" method="post">
            <p>* = required.</p>

            <input id="register-username" type="text" name="username" placeholder="Username*" required>
            <input id="register-email" type="email" name="email" placeholder="Email*" required>
            <input id="register-first_name" type="text" name="first_name" placeholder="First name">
            <input id="register-last_name" type="text" name="last_name" placeholder="Last name">
            <input id="register-password" type="password" name="password" placeholder="Password*" required>

            <button class="submit" type="submit" name="create" value="Register">Register</button>
            {% csrf_token %}
        </form><!-- #event-box -->
        <form id="register-cancel-box" action="{% url 'events:home' %}" method="POST">
            <button class="submit" type="submit" name="cancel" value="Cancel">Cancel</button>
            {% csrf_token %}
        </form>

{% endblock %}
{% block ad %}
    <div id="side-bar">
        <a href="#" class="ad"><img src="{% static "img/ad.jpg" %}" alt="Ad"></a>
        <a href="#" class="ad"><img src="{% static "img/ad.jpg" %}" alt="Ad"></a>
    </div><!-- #side-bar -->
{% endblock %}

templates/users/user/useredit_form.html
{% extends "events/base.html" %}
{% load static %}
{% block page-title %}Profile for {{ username.username }}{% endblock %}
{% block title %}
    <div id="title">
        <h2>Profile for {{ username.username }}</h2>
    </div><!-- #title -->
{% endblock %}
{% block content %}
    <div class="event-story">
        <form id="event-box" action="{% url 'users:update_profile' username.username %}" method="POST">
            <input id="edit-first-name" type="text" name="edit-first-name" value="{{ username.first_name }}" placeholder="First Name">
            <input id="edit-last-name" type="text" name="edit-last-name" value="{{ username.last_name }}" placeholder="Last Name">
            {% if request.session.role == "admin" or request.session.username == "admin" %}
                <input id="edit-role" type="text" name="edit-role" value="{{ username.role }}" placeholder="Edit Role">
            {% endif %}
            <input id="edit-password" type="text" name="edit-password" value="{{ username.password.decode }}" placeholder="Edit Password">

            <input id="save" class="button" type="submit" value="Save">
            {% csrf_token %}
        </form>
        <form id="discard-box" action="{% url 'users:profile' username.username %}" method="POST">
            <input id="delete" class="button" type="submit" value="Cancel">
            {% csrf_token %}
        </form>

    </div>

{% endblock %}