Django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls', namespace='events')),
    path('users/', include('users.urls', namespace='users'))
]

events/urls.py
from django.urls import path
from . import views
app_name = 'events'
urlpatterns = [
    # events_story views
    path('', views.home, name='home'),
    path('stories', views.events_story_list, name='story-list'),
    path('stories/<int:story_id>', views.events_story_detail, name='story-detail'),
    path('stories/add', views.create_event, name='create-event'),
    path('stories/new', views.event_added, name='event_added'),
    path('stories/results', views.search_results, name='search-results'),
    path('stories/results/none', views.search_results_none, name='search-results_none'),
    path('stories/edit/<int:story_id>', views.edit_event, name='edit'),
    path('stories/updated/<int:story_id>', views.event_changed, name='event_changed'),
    path('stories/delete/<int:story_id>', views.delete_event, name='delete'),
    path('stories/registered', views.events_story_registered, name='event_registered'),
    path('stories/liked', views.events_story_like, name='event_like'),
    path('stories/disliked', views.events_story_dislike, name='event_dislike'),
    path('stories/description', views.events_story_description, name='event_description'),
    path('stories/comments', views.view_comments, name='view_comments'),
    path('stories/comments/new', views.add_comment, name='add_comment'),
    path('stories/comments/edit/<int:comment_id>', views.edit_comment, name='edit_comment'),
    path('stories/comments/updated/<int:comment_id>', views.comment_changed, name='comment_changed'),
    path('stories/comment/delete/<int:comment_id>', views.delete_comment, name='delete_comment'),
    path('members', views.members, name='members'),
    path('contact', views.contact, name='contact'),
    path('media', views.media, name='media'),
    path('isvt', views.about, name='about'),
    path('directory', views.directory, name='directory'),
    path('join', views.join, name='join'),
    path('performer/facebook/<int:story_id>', views.performer_facebook, name='performer_facebook'),
    path('performer/facebook/added/<int:story_id>', views.performer_facebook_added, name='performer_facebook_added'),
]

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    # events_story views
    path('register', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('logout', views.logout_user, name='logout'),
    path('login', views.login_user, name='login'),
    path('update/<str:username>', views.update_profile, name='update_profile'),
    path('edit/<str:username>', views.edit_profile, name='edit_profile'),
]

events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.

class EventsStory(models.Model):
    title = models.CharField(max_length=200)
    date_month = models.CharField(max_length=50)
    date_day = models.CharField(max_length=20)
    date_weekday = models.CharField(max_length=50)
    time = models.CharField(max_length=50)
    score = models.IntegerField(default=0)
    author = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(auto_now_add=True)
    registered = models.IntegerField(default=0)
    description = models.TextField()
    performers = models.CharField(max_length=100)
    role = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    url = models.CharField(max_length=500)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('events:story-detail', args=[self.id])


class Comment(models.Model):
    title = models.CharField(max_length=200)
    comment = models.TextField()
    author = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('events:view_comments')


# hard-coded user accounts
regular_user = {"username": "rana", "password": "regular"}
admin_user = {"username": "admin", "password": "admin"}

events/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import regular_user, admin_user, EventsStory, User, Comment
from actions.models import Action
from django.http import JsonResponse
import requests
import boto3
from django.template.loader import render_to_string
from django.contrib.auth import authenticate


# Create your views here.
def events_story_list(request):
    events_stories = EventsStory.objects.all()
    sort = request.POST.get('sort-by-register')
    if sort == 'Registered':
        events_stories = EventsStory.objects.order_by('-registered')
    sort1 = request.POST.get('sort-by-date')
    if sort1 == 'Recently updated':
        events_stories = EventsStory.objects.order_by('-date_posted')
    return render(request,
                  "events/events_story/list.html",
                  {"stories": events_stories}
                  )


def events_story_detail(request, story_id):
    story = EventsStory.objects.get(pk=story_id)

    endpoint = "https://en.wikipedia.org/w/api.php"
    parameters = {
        "action": "query",
        "list": "search",
        "srsearch": story.title,
        "format": "json",
    }

    try:
        response = requests.get(endpoint, params=parameters)
        wikidata = response.json()
        top_wiki_title = wikidata["query"]["search"][0]["title"]
    except IndexError:
        top_wiki_title = None

    return render(request,
                  "events/events_story/detail.html",
                  {"story": story,
                   "top_wiki_title": top_wiki_title}
                  )


def home(request):
    if request.session.get("username", False):
        actions = Action.objects.all().order_by('-created')

        return render(request,
                      "events/events_story/dashboard.html",
                      {"actions": actions}
                      )

    else:
        return render(request,
                      "events/home.html",
                      )


def create_event(request):
    return render(request,
                  "events/events_story/add.html",
                  )


def event_added(request):
    if request.method == 'POST':
        # process the form
        title = request.POST.get('add-title')
        description = request.POST.get('add-description')
        startdate = request.POST.get('add-start date')
        starttime = request.POST.get('add-start time')
        location = request.POST.get('add-location')
        guests = request.POST.get('add-guests')
        role = request.POST.get('add-role')

        # content moderation
        endpoint = "https://isvttextmod.cognitiveservices.azure.com/contentmoderator/moderate/v1.0/ProcessText/Screen"
        parameters = {
            'classify': True,
        }
        headers = {
            'Content-Type': 'text/plain',
            'Ocp-Apim-Subscription-Key': '5d85180a097b4949ba5bc2b583c6569f',
        }
        data = description
        response = requests.post(endpoint, params=parameters, headers=headers, data=data)
        response_json = response.json()
        review_recommended = response_json["Classification"]["ReviewRecommended"]
        if review_recommended:
            messages.add_message(request, messages.ERROR,
                                 "Your description contains inappropriate contents. Please change it.")
            return redirect('events:create-event')

        user = User.objects.get(username=request.session.get("username"))

        es = EventsStory(
            title=title,
            description=description,
            date_weekday=startdate,
            date_month=startdate,
            # date_day=startdate,
            time=starttime,
            location=location,
            performers=guests,
            author=request.session.get('username'),
            user=user,
            role=role,
        )
        es.save()

        # log the action
        action = Action(
            user=user,
            verb="created the new story",
            target=es
        )
        action.save()
        messages.add_message(request, messages.SUCCESS, "You successfully submitted a new event story: %s" % es.title)
        element = es
        return redirect('events:story-detail', element.id)
    else:
        # show the template
        return render(request,
                      "events/events_story/add.html",
                      )


def edit_event(request, story_id):
    story = EventsStory.objects.get(pk=story_id)
    return render(request,
                  "events/events_story/edit.html",
                  {"story": story}
                  )


def event_changed(request, story_id):

    es = EventsStory.objects.get(pk=story_id)

    mturk = request.GET.get('mturk', False)
    if mturk == 'yes':
        user = authenticate(username='mturk', password='mturk')
        request.session['username'] = user.username
        request.session['role'] = user.details.role
    else:
        user = User.objects.get(username=request.session.get("username"))

    if user.id == es.user.id or request.session['role'] == 'admin' or user.username == 'mturk':
        if request.method == 'POST':
            # process the form
            title = request.POST.get('edit-title')
            description = request.POST.get('edit-description')
            print(description)
            startdate = request.POST.get('edit-date')
            starttime = request.POST.get('edit-time')
            location = request.POST.get('edit-location')
            guests = request.POST.get('edit-guests')
            print(guests)
            role = request.POST.get('edit-role')
            print(role)

            if title:
                es.title = title
            if description:
                es.description = description
            if startdate:
                es.startdate = startdate
            if starttime:
                es.starttime = starttime
            if location:
                es.location = location
            if guests:
                es.guests = guests
            if role:
                es.role = role
            es.save()

            # log the action
            action = Action(
                user=user,
                verb="edited a story",
                target=es
            )
            action.save()

            messages.add_message(request, messages.SUCCESS, "You successfully edited an event story: %s" % es.title)
            element = es
            return redirect('events:story-detail', story_id=story_id)
        else:
            # show the template
            return render(request,
                          "events/events_story/edit.html",
                          )


def delete_event(request, story_id):
    instance = EventsStory.objects.get(id=story_id)
    instance.delete()

    messages.add_message(request, messages.WARNING, "The following event story was deleted: %s" % instance.title)

    return redirect('events:story-list')


def events_story_registered(request):
    # redirect if not logged in
    if not request.session.get("username", False):
        return redirect('events:story-list')

    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        story_id = request.POST.get('story_id')
        try:
            story = EventsStory.objects.get(pk=story_id)
            story.registered = story.registered + 1
            story.save()
            return JsonResponse({'success': 'success', 'registered': story.registered}, status=200)

        except EventsStory.DoesNotExist:
            return JsonResponse({'error': 'No story found with that ID.'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax request.'}, status=400)


def events_story_like(request):
    # redirect if not logged in
    if not request.session.get("username", False):
        return redirect('events:story-list')

    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        story_id = request.POST.get('story_id')
        try:
            story = EventsStory.objects.get(pk=story_id)
            story.score = story.score + 1
            story.save()
            return JsonResponse({'success': 'success', 'score': story.score}, status=200)

        except EventsStory.DoesNotExist:
            return JsonResponse({'error': 'No story found with that ID.'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax request.'}, status=400)


def events_story_dislike(request):
    # redirect if not logged in
    if not request.session.get("username", False):
        return redirect('events:story-list')

    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        story_id = request.POST.get('story_id')
        try:
            story = EventsStory.objects.get(pk=story_id)
            story.score = story.score - 1
            story.save()
            return JsonResponse({'success': 'success', 'score': story.score}, status=200)

        except EventsStory.DoesNotExist:
            return JsonResponse({'error': 'No story found with that ID.'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax request.'}, status=400)


def events_story_description(request):
    # redirect if not logged in
    if not request.session.get("username", False):
        return redirect('events:home')

    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "GET":
        # story_id = request.POST.get('story_id')
        try:
            story = EventsStory.objects.all()
            story.info = story.info
            story.save()
            return JsonResponse({'success': 'success', 'info': story.info}, status=200)

        except EventsStory.DoesNotExist:
            return JsonResponse({'error': 'No data found with that ID.'}, status=200)

templates/events/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>Iranian Society of Virginia Tech | {% block page-title %}{% endblock %}</title>
        {% block scripts %}
            <script src="{% static "JS/jquery-3.6.0.min.js" %}"></script>
            <script src="{% static "JS/scripts.js" %}"></script>
        {% endblock %}
        <link rel="stylesheet" type="text/css" href="{% static "CSS/responsive.css" %}">
    </head>
    <body>
    <div id="header">

        <div id="title-box">
            <!-- #image from ISVT media group in Telegram -->
            <img src="{% static "img/Logo.png" %}" alt="Logo">
            <h4>ISVT</h4>
            <h5>Iranian Society at Virginia Tech</h5>
        </div><!-- #title-box -->

        <form id="search-box" action="{% url 'events:search-results_none' %}" method="GET">
            <input type="search" name="search" placeholder="search">
        </form><!-- #search-box -->

        {% if request.session.username %}

            <form id="Logged-in">
                <p>Logged in as <a href="{% url "users:profile" request.session.username %}" ><strong>{{ request.session.username }}</strong></a></p>
                <a href="{% url 'users:logout' %}">Log out</a>
            </form><!-- #Login-box -->

        {% else %}

            <form id="Login-box" action="{% url 'users:login' %}" method="POST">
                {% csrf_token %}
                <input type="text" name="username" placeholder="username">
                <input type="password" name="pw" placeholder="password">
                <input type="submit" name="submit" value="log in"> or <a href="{% url 'users:register' %}">Join</a>
            </form><!-- #Login-box -->

        {% endif %}


        <ul id="primary-nav">
            <li><a href="{% url 'events:home' %}">Home</a></li>
            <li><a href="#" class="about-parent">
                <div class="fold">
                    <span id="text">About</span>
                </div>
                </a>
            </li>
            <li><a href="{% url 'events:story-list' %}">Programs and Events</a></li>
            <li><a href="{% url 'events:members' %}">Members</a></li>
            <li><a href="{% url 'events:media' %}">Media</a></li>
            <li><a href="{% url 'events:contact' %}">Contact</a></li>
        </ul><!-- #primary-nav -->

    </div><!-- #header -->
    <div id="content">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <div id="title">
            {% block title %}{% endblock %}
        </div><!-- #title -->

        <div id="filter-box">
            {% block filter %}{% endblock %}
        </div><!-- #filter-box -->

        <div id="events">
            {% block content %}{% endblock %}
        </div><!-- #events -->


        <div id="side-bar">
            {% block ad %}{% endblock %}
        </div><!-- #side-bar -->
    </div><!-- #content -->

    <div id="footer">
        <p id="copyright">Copyright 2021 Iranian Society at VT</p>
        <div id="social">
            <a href="https://www.facebook.com/groups/248093027376">Facebook</a>
            <a href="#">Twitter</a>
            <a href="#">Instagram</a>
        </div><!-- #social -->

        <p id="menu"><a href="#">Policies</a> | <a href="#">Contact</a>

    </div><!-- #footer -->

    </body>
</html>

templates/events/home.html
{% extends "events/base.html" %}
{% load static %}
{% block page-title %}Home{% endblock %}
{% block content %}
    <div id="image-box">
            <!-- #image from ISVT media group in Telegram -->
        <img src="{% static "img/intro.JPG" %}" alt="Intro">
        </div><!-- #image-box -->

        <div id="intro-text">
            <h1>Iranian Society at Virginia Tech</h1>
            <button class="load" data-ajax-url="{% url 'events:event_description' %}">Click me to load info!</button>
            <div class="info"></div>

        </div><!-- #intro-text -->

        <div id="image-box2">
            <!-- #image made by RaenaRahimiBafrani -->
            <img src="{% static "img/Calendar-September-2021.JPG" %}" alt="Calendar">
            <!-- #image from ISVT media group in Telegram -->
            <img src="{% static "img/yaldanight.jpeg" %}" alt="Flyer">
            <img src="{% static "img/mehregan.jpeg" %}" alt="Flyer">
            <img src="{% static "img/chiptole-fundrising.jpeg" %}" alt="Flyer">
            <img src="{% static "img/flyer.jpeg" %}" alt="Flyer">
        </div><!-- #image-box2 -->
{% endblock %}